tyohuonekattovalot:
  module: controllerx
  class: E1810Controller
  controller: tyohuone
  integration: deconz
  light: light.tyohuone
  mapping:
    2001: hold_brightness_up
    2002: click_brightness_up
    2003: release
    3001: hold_brightness_down
    3002: click_brightness_down
    3003: release
    4001: hold_colortemp_up
    4002: click_colortemp_up
    4003: release
    5001: hold_colortemp_down
    5002: click_colortemp_down
    5003: release  
tyohuonekattovaloton:
  module: controllerx
  class: CallServiceController
  controller: tyohuone
  integration: deconz
  mapping: 
   1002:
    - service: light.toggle
      data:
        entity_id: light.tyohuone
        brightness: 100
olohuonepienet:
  module: controllerx
  class: E1810Controller
  controller: olohuone_pieni
  integration: deconz
  light: light.olohuone_pieni
  mapping:
    2001: hold_brightness_up
    2002: click_brightness_up
    2003: release
    3001: hold_brightness_down
    3002: click_brightness_down
    3003: release
    4001: hold_colortemp_up
    4002: click_colortemp_up
    4003: release
    5001: hold_colortemp_down
    5002: click_colortemp_down
    5003: release  
olohuonepieneton:
  module: controllerx
  class: CallServiceController
  controller: olohuone_pieni
  integration: deconz
  mapping: 
   1002:
    - service: light.toggle
      data:
        entity_id: light.olohuone_pieni
        brightness: 150
olohuoneisot:
  module: controllerx
  class: E1810Controller
  controller: olohuone_iso
  integration: deconz
  light: light.olohuone_iso
  mapping:
    2001: hold_brightness_up
    2002: click_brightness_up
    2003: release
    3001: hold_brightness_down
    3002: click_brightness_down
    3003: release
    4001: hold_colortemp_up
    4002: click_colortemp_up
    4003: release
    5001: hold_colortemp_down
    5002: click_colortemp_down
    5003: release  
olohuoneisoton:
  module: controllerx
  class: CallServiceController
  controller: olohuone_iso
  integration: deconz
  mapping: 
   1002:
    - service: light.toggle
      data:
        entity_id: light.olohuone_iso
        brightness: 200
leikkihuone:
  module: controllerx
  class: E1810Controller
  controller: leikkihuone
  integration: deconz
  light: light.leikkihuone
  mapping:
    2001: hold_brightness_up
    2002: click_brightness_up
    2003: release
    3001: hold_brightness_down
    3002: click_brightness_down
    3003: release
    4001: hold_colortemp_up
    4002: click_colortemp_up
    4003: release
    5001: hold_colortemp_down
    5002: click_colortemp_down
    5003: release
leikkihuoneon:
  module: controllerx
  class: CallServiceController
  controller: leikkihuone
  integration: deconz
  mapping: 
   1002:
    - service: light.toggle
      data:
        entity_id: light.leikkihuone
        brightness: 200
tyohuonelednauhat:
  module: controllerx
  class: E1810Controller
  controller: tyohuone_lednauhat
  integration: deconz
  light: light.tyohuone_lednauha
  mapping:
    2001: hold_brightness_up
    2002: click_brightness_up
    2003: release
    3001: hold_brightness_down
    3002: click_brightness_down
    3003: release
tyohuonelednauhaton:
  module: controllerx
  class: CallServiceController
  controller: tyohuone_lednauhat
  integration: deconz
  mapping: 
   1002:
    - service: light.toggle
      data:
        entity_id: light.tyohuone_lednauha
        brightness: 150
replay_lights:
  module: replay_lights
  class: ReplayLights
  numberOfDaysBack: 7
  databaseType: "MariaDB"
  databasePassword: !secret dbpassword
  deviceType: "light"
  enableTag: "input_boolean.awaymode"
  enableVal: "on"
  excludeList: "light.isowc1,light.isowc2,light.isowc3,light.isowc4,light.isowc5,light.isowc6,light.olohuone_kaikki_valot"
replay_lights_switch:
  module: replay_lights
  class: ReplayLights
  numberOfDaysBack: 7
  databaseType: "MariaDB"
  databasePassword: !secret dbpassword
  deviceType: "switch"
  enableTag: "input_boolean.awaymode"
  enableVal: "on"
  excludeList: "switch.shelly_shsw_1_bcddc277746f,switch.patteri,switch.octavia,switch.golf"