- id: decoration_ligths_on
  alias: Valot päälle ennen aurinkolaskua
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0
  action:
    service: switch.turn_on
    entity_id: group.koristevalot
- id: decoration_ligths_off
  alias: Valot pois klo 23 ja aamulla kun aurinko on noussut
  trigger:
  - platform: time
    at: '23:10'
  - platform: time
    at: '08:00'
  action:
  - service: switch.turn_off
    entity_id: group.koristevalot
- id: decoration_ligths_tree_on
  alias: Kuusen valot päälle ennen aurinkolaskua
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0
  - platform: time
    at: '8:30'
  condition:
  - condition: time
    after: '7:20:00'
    before: '19:40:00'
  action:
    service: switch.turn_on
    entity_id: switch.tradfri_outlet_7
- id: decoration_ligths_tree_off
  alias: Kuusen valot pois klo 19:50 ja aamulla kun aurinko on noussut
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 0
  - platform: time
    at: '19:50'
  action:
  - service: switch.turn_off
    entity_id: switch.tradfri_outlet_7
- id: night_lights_on
  alias: Yövalot päälle ennen nukkumaan menoa
  trigger:
  - platform: time
    at: '18:30'
  action:
    service: switch.turn_on
    entity_id: switch.makuuhuone
- id: night_lights_off
  alias: Yövalot pois aamulla klo 8:30
  trigger:
  - platform: time
    at: '8:30'
  action:
  - service: switch.turn_off
    entity_id: switch.makuuhuone
- id: phone_outlet_on
  alias: Pistorasia päälle kun akku on tyhja
  trigger:
  - platform: numeric_state
    entity_id: sensor.puhelin1
    below: 90
  - platform: time
    at: '22:00'
  action:
    service: switch.turn_on
    entity_id: switch.tradfri_outlet_2
- id: phone_outlet_off
  alias: Pistorasia pois kun akku täynnä
  trigger:
  - platform: numeric_state
    entity_id: sensor.puhelin1
    above: 99
  action:
  - service: switch.turn_off
    entity_id: switch.tradfri_outlet_2
- id: fireplace_fan_on
  alias: Puhallus päälle kun takka on päällä
  trigger:
  - platform: numeric_state
    entity_id: sensor.takka_temperature
    above: 35
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.pumppu
      hvac_mode: fan_only
  - service: climate.set_fan_mode
    data:
      entity_id: climate.pumppu
      fan_mode: LowMid
- id: fireplace_fan_off
  alias: Puhallus pois kun takka on kylmä
  trigger:
  - platform: numeric_state
    entity_id: sensor.takka_temperature
    below: 45
    for:
      minutes: 1
  condition:
  - condition: state
    entity_id: climate.pumppu
    state: fan_only
  action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.pumppu
      hvac_mode: heat
  - service: climate.set_fan_mode
    data:
      entity_id: climate.pumppu
      fan_mode: Auto
- id: pool_heating_on
  alias: Aurinkokenno on lämmin
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.aurinkenno_temperature'')|float +1 > states(''sensor.uima_allas_temperature'')|float}}'
  - platform: time_pattern
    minutes: '/10'
  condition:
  - condition: time
    after: '9:00:00'
    before: '21:00:00'
  - condition: state
    entity_id: input_boolean.pumppu
    state: 'off'
  - condition: template
    value_template: '{{ states(''sensor.aurinkenno_temperature'')|float +1 > states(''sensor.uima_allas_temperature'')|float}}'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.pumppu
  - service: switch.turn_on
    entity_id: switch.patteri
  - service: telegram_bot.send_message
    data_template:
      title: '*Uima-altaan pumppu päälle*'
      target: !secret telegram_chat3
      message: Aurinkokenno on {{ states('sensor.aurinkenno_temperature') }} ja uima-allas
        {{ states('sensor.uima_allas_temperature') }}
- id: pool_heating_off
  alias: Aurinkokenno jäähdyttää
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.uima_allas_tulo_temperature'')|float < states(''sensor.uima_allas_temperature'')|float}}'
  - platform: time_pattern
    minutes: '/5'
  condition:
  - condition: time
    after: '9:00:00'
    before: '21:00:00'
  - condition: template
    value_template: '{{ states(''sensor.uima_allas_tulo_temperature'')|float < states(''sensor.uima_allas_temperature'')|float}}'
  - condition: state
    entity_id: input_boolean.pumppu
    state: 'on'
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.pumppu
  - service: switch.turn_off
    entity_id: switch.patteri
  - service: telegram_bot.send_message
    data_template:
      title: '*Uima-altaan pumppu pois päältä*'
      target: !secret telegram_chat3
      message: Tulo on {{ states('sensor.uima_allas_tulo_temperature') }} ja uima-allas
        {{ states('sensor.uima_allas_temperature') }}
- id: golf_heating_on
  alias: Golf lämmitys
  trigger:
  - platform: state
    entity_id: binary_sensor.golf_0b
    to: 'on'
  - platform: state
    entity_id: binary_sensor.golf_10b
    to: 'on'
  - platform: state
    entity_id: binary_sensor.golf_20b
    to: 'on'
  - platform: state
    entity_id: switch.golf
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: switch.golf
        state: 'on'
      - condition: state
        entity_id: timer.golf
        state: idle
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.golf_0b
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.autotalli_temperature
        below: 10
      - condition: state
        entity_id: input_boolean.golf
        state: 'on'
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.golf_10b
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.autotalli_temperature
        below: -10
      - condition: state
        entity_id: input_boolean.golf
        state: 'on'
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.golf_20b
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.autotalli_temperature
        below: -20
      - condition: state
        entity_id: input_boolean.golf
        state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.autojen_lammitys
    data:
      variables:
        car: timer.golf
  - service: switch.turn_on
    entity_id: switch.golf
  - service: telegram_bot.send_message
    data_template:
      title: '*Golf lämmitys päälle*'
      target: !secret telegram_chat3
      message: 'Pyydetty lämmitysaika:  {% if is_state(''input_boolean.golf'', ''on'')  -%}{{
        states(''input_datetime.golf'') }} {%- else -%}Käynnistetty käsin{%- endif
        %} autotallin lämpötila on {{ states(''sensor.autotalli_temperature'') }}'
  - service: input_boolean.turn_off
    entity_id: input_boolean.golf
- id: golf_heating_off
  alias: Golf lämmitys pois
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.golf
  action:
  - service: switch.turn_off
    entity_id: switch.golf
  - service: telegram_bot.send_message
    data_template:
      title: '*Golf lämmitys pois*'
      target: !secret telegram_chat3
      message: 'Pyydetty lämmitysaika oli:  {{ states(''input_datetime.golf'') }}
        autotallin lämpötila on {{ states(''sensor.autotalli_temperature'') }}'
- id: ocatavia_heating_on
  alias: Octavia lämmitys
  trigger:
  - platform: state
    entity_id: binary_sensor.octavia_0b
    to: 'on'
  - platform: state
    entity_id: binary_sensor.octavia_10b
    to: 'on'
  - platform: state
    entity_id: binary_sensor.octavia_20b
    to: 'on'
  - platform: state
    entity_id: switch.octavia
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: switch.octavia
        state: 'on'
      - condition: state
        entity_id: timer.octavia
        state: idle
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.octavia_0b
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.autotalli_temperature
        below: 10
      - condition: state
        entity_id: input_boolean.octavia
        state: 'on'
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.octavia_10b
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.autotalli_temperature
        below: -10
      - condition: state
        entity_id: input_boolean.octavia
        state: 'on'
    - condition: and
      conditions:
      - condition: state
        entity_id: binary_sensor.octavia_20b
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.autotalli_temperature
        below: -20
      - condition: state
        entity_id: input_boolean.octavia
        state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.autojen_lammitys
    data:
      variables:
        car: timer.octavia
  - service: switch.turn_on
    entity_id: switch.octavia
  - service: telegram_bot.send_message
    data_template:
      title: '*Octavia lämmitys päälle*'
      target: !secret telegram_chat3
      message: 'Pyydetty lämmitysaika:  {% if is_state(''input_boolean.octavia'',
        ''on'')  -%}{{ states(''input_datetime.octavia'') }} {%- else -%}Käynnistetty
        käsin{%- endif %} autotallin lämpötila on {{ states(''sensor.autotalli_temperature'')
        }}'
  - service: input_boolean.turn_off
    entity_id: input_boolean.octavia
- id: ocatavia_heating_off
  alias: Octavia lämmitys pois
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.octavia
  action:
  - service: switch.turn_off
    entity_id: switch.octavia
  - service: telegram_bot.send_message
    data_template:
      title: '*Octavia lämmitys pois*'
      target: !secret telegram_chat3
      message: 'Pyydetty lämmitysaika oli:  {{ states(''input_datetime.octavia'')
        }} autotallin lämpötila on {{ states(''sensor.autotalli_temperature'') }}'
- id: Evening_scene_on
  alias: Olohuoneen valot himmeälle illala
  trigger:
  - platform: state
    entity_id: media_player.samsung_ue55ku6075_2
    to: 'on'
  condition:
  - condition: time
    after: '20:00:00'
    before: '23:00:00'
  action:
  - service: scene.turn_on
    entity_id: scene.evening
  - service: media_player.volume_set
    data:
      entity_id: media_player.samsung_tv_remote
      volume_level: 0
- id: heatpump_to_cooling_evening
  alias: Pumppu viilennykselle aamulla
  trigger:
  - platform: time
    at: '23:30'
  condition:
  - condition: numeric_state
    entity_id: sensor.sisa_temperature
    above: 23
  action:
  - service: climate.turn_on
    entity_id: climate.pumppu
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.pumppu
      hvac_mode: cool
  - service: climate.set_temperature
    data:
      entity_id: climate.pumppu
      temperature: 20
- id: heatpump_off_morning
  alias: Pumppu  pois aamulla
  trigger:
  - platform: time
    at: '05:50'
  action:
  - service: climate.turn_off
    entity_id: climate.pumppu
- id: garage_doors_check
  alias: Tarkista autotallin ovet
  trigger:
    platform: time
    at: '21:00'
  condition:
    condition: template
    value_template: '{{ states | selectattr(''entity_id'', ''in'', state_attr(''group.autotallinovet'',''entity_id''))
      | selectattr(''state'',''in'',[''on'',''open'']) | list | length >= 1 }}

      '
  action:
  - service: telegram_bot.send_message
    data_template:
      title: '*Autotallin ovet on auki*'
      target: !secret telegram_chat3
      message: '{% set open_doors = states | selectattr(''entity_id'', ''in'', state_attr(''group.autotallinovet'',''entity_id''))
        | selectattr(''state'',''in'',[''on'',''open'']) | map(attribute=''name'')
        | list %} {% if open_doors | length == 1 %} {{ open_doors[0] }} on auki. {%
        else %} {{ open_doors[:-1] | join('', '') }}{{'''' if open_doors | length
        > 2 else '' ''}} ja {{ open_doors[-1]}} on auki. {% endif %}'
- id: All_lights_off
  alias: Kaikki valot pois
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: eteinen
      event: 4002
  action:
  - service: switch.turn_off
    entity_id: switch.olohuone1
  - service: light.turn_off
    entity_id: light.olohuone_kaikki_valot
- id: Bathroom_light
  alias: Pikkuvessan valot
  trigger:
    platform: state
    entity_id: binary_sensor.presence_9
    to: 'on'
  condition:
  - condition: time
    after: '6:00:01'
    before: '23:30:00'
  - condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5
  action:
  - service: light.turn_on
    data:
      entity_id: light.koristevalo
      brightness: 150
- id: Bathroom_light_night
  alias: Pikkuvessan valot yöllä
  trigger:
    platform: state
    entity_id: binary_sensor.presence_9
    to: 'on'
  condition:
  - condition: time
    after: '23:30:01'
    before: '06:00:00'
  action:
  - service: light.turn_on
    data:
      entity_id: light.koristevalo
      brightness: 10
- id: Bathroom_light_off
  alias: Vessan valot pois
  trigger:
    platform: state
    entity_id: binary_sensor.presence_9
    to: 'off'
    for:
      minutes: 5
  action:
  - service: light.turn_off
    entity_id: light.koristevalo
- id: Playroom_light
  alias: Leikkihuoneen valot
  trigger:
    platform: state
    entity_id: binary_sensor.presence_19
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.leikkihuone
      brightness: 200
- id: Leikkihuoneen_light_off
  alias: Leikkihuoneen valot pois
  trigger:
    platform: state
    entity_id: binary_sensor.presence_19
    to: 'off'
    for:
      minutes: 15
  action:
  - service: light.turn_off
    entity_id: light.leikkihuone
- id: Garage_door_closed
  alias: Autotallin ovi kiinni
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: eteinen
      event: 5002
  condition:
  - condition: state
    entity_id: cover.autotallin_ovi
    state: open
  - condition: state
    entity_id: timer.garagedooropen
    state: idle
  action:
  - service: cover.close_cover
    entity_id: cover.autotallin_ovi
- id: Garage_door_timer
  alias: Autotallin ovi ajastin
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: eteinen
      event: 5002
  condition:
  - condition: state
    entity_id: cover.autotallin_ovi
    state: closed
  action:
  - service: timer.start
    data:    
      entity_id: timer.garagedooropen
      duration: '0:05:00'
- id: Garage_door_open
  alias: Autotallin ovi auki
  trigger:
    platform: state
    entity_id: binary_sensor.openclose_20
    to: 'on'
  condition:
  - condition: state
    entity_id: timer.garagedooropen
    state: active
  - condition: state
    entity_id: cover.autotallin_ovi
    state: closed
  action:
  - service: cover.open_cover
    entity_id: cover.autotallin_ovi
- id: Bathroom_lights
  alias: Ison vessan valot
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: isowc
      event: 1002
  condition:
  - condition: time
    after: '6:00:00'
    before: '21:00:00'
  action:
  - service: light.toggle
    data:
      entity_id: light.wc
      brightness: 120
  - service: switch.toggle
    entity_id: switch.shelly_shsw_1_bcddc277746f
- id: Bathroom_lights_night
  alias: Ison vessan valot yöllä
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: isowc
      event: 1002
  condition:
  - condition: time
    after: '21:00:01'
    before: '05:59:59'
  action:
  - service: light.toggle
    data:
      entity_id: light.Isowc1
      brightness: 1