koristevalot:
  name: Koristevalot
  entities:
    - switch.leikkihuone
    - switch.vierashuone
    - switch.olohuone1
    - switch.olohuone2
    - switch.keittio
    - switch.tyohuone

autotallinovet:
  name: Autotallin ovet
  entities:
     - binary_sensor.puutarhavarasto
     - binary_sensor.sivuovi
     - binary_sensor.kylmavarasto
     - binary_sensor.autotallin_ovi