koristevalot:
  name: Koristevalot
  entities:
    - switch.tradfri_outlet_5
    - switch.tradfri_outlet_4
    - switch.tradfri_outlet_3
autotallinovet:
  name: Autotallin ovet
  entities:
     - binary_sensor.puutarhavarasto
     - binary_sensor.sivuovi
     - binary_sensor.kylmavarasto
     - binary_sensor.autotallin_ovi