autojen_lammitys:
  description: 'Cars heating time'
  alias: 'Autojen lämmitysaika'
  fields:
    car:
      description: 'name of the car'
      example: 'octavia'
  sequence:
    - condition: numeric_state
      entity_id: sensor.autotalli_temperature
      above: 5
    - service: timer.start
      data_template:
        entity_id: "{{ car }}"
        duration: '00:30:00'
    - condition: numeric_state
      entity_id: sensor.autotalli_temperature
      below: 5
    - service: timer.start
      data_template:
        entity_id: "{{ car }}"
        duration: '01:00:00'
    - condition: numeric_state
      entity_id: sensor.autotalli_temperature
      below: -10
    - service: timer.start
      data_template:
        entity_id: "{{ car }}"
        duration: '01:30:00'
    - condition: numeric_state
      entity_id: sensor.autotalli_temperature
      below: -20
    - service: timer.start
      data_template:
        entity_id: "{{ car }}"
        duration: '02:30:00'